Add stataUSDC
Synthetixio/liquidity-ui pull request #9
Opened 2024-09-24 02:49 UTC by barrasso

The plan is to change this to USDC deposit but take the user through the stataUSDC conversion flow before finally depositing stataUSDC into the vault.

![image](https://github.com/user-attachments/assets/fb197f4f-0fd2-44fb-bce4-fe08eaea6b87)

2024-09-27 06:14 UTC, noisekit requested changes
The main blocker is symbol comparisons, need to compare addresses.

Plus few things to refactor

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/ConvertStataUSDCTransaction.tsx
> +        : utils.parseUnits(amount.toString(), USDC?.decimals)
remove hardcoded decimal and isBase check

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/ConvertStataUSDCTransaction.tsx
> +  useEffect(() => {
pass `onSuccess` callback to mutation and remove useEffect

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/ConvertStataUSDCTransaction.tsx
> +            This will convert <Amount value={amount} suffix={` USDC `} /> to stataUSDC
```suggestion
            This will convert <Amount value={amount} suffix={` USDC`} /> to stataUSDC
```

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/ConvertStataUSDCTransaction.tsx
> +      {txState.status !== 'pending' && (
switch from `&&` to `? : null` ternary

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/StepIntro.tsx
> +    //TODO: Get stataUSDC exchange rate
resolve this todo because stataUSDC is not 1:1. It is noticeably higher

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/StepIntro.tsx
> +  useEffect(() => {
replace with useQuery

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/components/Manage/CollateralStats.tsx
> +                  collateralType.displaySymbol === 'stataUSDC'
we already hardcode dysplay symbols manually, move it there please and remove this branching

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/components/Rewards/Rewards.tsx
> +            {isLoading ? <RewardsLoading /> : null}
Revert this. It we only need to show loader on the first load. not flash whole block on every refetch. This change was intentional.

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/components/Rewards/Rewards.tsx
> +            ) : (
keep `null` here and add one more specific condition to display
This change should go into a separate pr if possible as it is not related to stataUSDC

2024-09-27 06:14 UTC, noisekit commented on liquidity/ui/src/layouts/Default/Header.tsx
> +            )}
```suggestion
            {network && [BASE_ANDROMEDA.id, BASE_SEPOLIA.id] ? (
              <ConvertStataUSDCButton network={network} />
            ) : null}
```

2024-09-27 06:16 UTC, noisekit commented on liquidity/cypress/cypress/e2e/8453-andromeda/Manage StataUSDC Position - Deposit.e2e.js
> +    .and('include.text', 'Wrap USDC into stataUSDc')
```suggestion
    .and('include.text', 'Wrap USDC into stataUSDC')
```

2024-09-27 06:16 UTC, noisekit commented on liquidity/cypress/cypress/e2e/8453-andromeda/Manage StataUSDC Position - Deposit.e2e.js
> +    .and('include.text', 'Deposit and Lock stataUSDc')
```suggestion
    .and('include.text', 'Deposit and Lock stataUSDC')
```

2024-09-27 06:21 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/StepSuccess.tsx
> +      */}
```suggestion
```

2024-09-27 06:22 UTC, noisekit commented on liquidity/ui/src/components/InitialDeposit/InitialDeposit.tsx
> +    collateralSymbol === 'stataUSDC' ? 'USDC' : collateralSymbol
We cannot just show USDC and operate with stataUSDC underneath. stataUSDC price is not 1:1 to USDC, it is not just a 1:1 sUSDC wrapper anymore. We should display it the same way as we display any other non-USDC collateral on non-andromeda deploymens.

2024-09-27 06:48 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/StepIntro.tsx
> +    //TODO: Get stataUSDC exchange rate
I believe we need to use `useOraclePrice` for this.

2024-09-27 08:57 UTC, MrX-SNX commented on liquidity/cypress/cypress/e2e/8453-andromeda/Manage StataUSDC Position - Deposit.e2e.js
> +    .and('include.text', 'Wrap USDC into stataUSDc')
@thisispixelperfect like that its in the design

2024-09-27 09:10 UTC, MrX-SNX commented on liquidity/ui/src/components/ConvertStataUSDC/ConvertStataUSDCTransaction.tsx
> +  const { data: stataUSDC } = useCollateralType('stataUSDC');
so why did you wrote this hook that accepts a symbol?

2024-09-27 09:51 UTC, MrX-SNX commented on liquidity/ui/src/components/Rewards/Rewards.tsx
> +            ) : (
no this needs to stay cause you never will see `Create a position ...`

2024-09-27 10:50 UTC, MrX-SNX commented on liquidity/lib/isBaseAndromeda/isBaseAndromeda.ts
> +};
it will stay like that

2024-09-27 11:06 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/ConvertStataUSDCTransaction.tsx
> +  const { data: stataUSDC } = useCollateralType('stataUSDC');
Because it made sense a year agond a half ago and it no longer correct and we need to change it. We have duplicate symbols and also have symbols that are different in different deployments 
from now on please use addresses and do not use symbols to avoid incorrect behaviour

2024-09-27 11:07 UTC, noisekit commented on liquidity/lib/isBaseAndromeda/isBaseAndromeda.ts
> +};
Elaborate please.

2024-09-27 11:12 UTC, noisekit commented on liquidity/ui/src/components/Rewards/Rewards.tsx
> +            ) : (
You add a separate ternary with exact condition that should trigger this element to be visible.

2024-09-27 11:13 UTC, noisekit commented on liquidity/cypress/cypress/e2e/8453-andromeda/Manage StataUSDC Position - Deposit.e2e.js
> +    .and('include.text', 'Wrap USDC into stataUSDc')
It is a typo.

2024-09-30 01:52 UTC, noisekit commented on liquidity/cypress/cypress/e2e/8453-andromeda/Manage USDC Position - Deposit.e2e.js
> +  cy.get('[data-cy="deposit amount input"]').should('exist').type('120');
```suggestion
  cy.get('[data-cy="deposit amount input"]').should('exist').type('101');
```

2024-09-30 01:57 UTC, noisekit commented on liquidity/lib/useApr/useStataUSDCApr.ts
> +          reserve.underlyingAsset === '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913'
shouldn't this be part of the query filter? here we are filtering end result and can get incorrect results.

2024-09-30 01:58 UTC, noisekit commented on liquidity/lib/useApr/useStataUSDCApr.ts
> +        'https://gateway.thegraph.com/api/f55095f3203bcba72cbee045322be46c/subgraphs/id/GQFbb95cE6d8mV989mL5figjaGaKCQB3xqYrr1bRyXqF',
what is this graph?

2024-09-30 02:00 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/ConvertStataUSDCButton.tsx
> +  useEffect(() => {
switch to `useParams`, please look through the code and update all places like this, not just ones I pointed out.

2024-09-30 02:01 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/ConvertStataUSDCTransaction.tsx
> +  const USDCCollateral = collateralTypes?.filter(
extract into a library function as this chunk of code is repeated multiple time.
Use Array.find / Array.some instead.

2024-09-30 02:02 UTC, noisekit commented on liquidity/ui/src/components/ConvertStataUSDC/ConvertStataUSDCTransaction.tsx
> +        title: 'Migration failed',
is is migration?

2024-10-10 08:33 UTC, noisekit commented on liquidity/lib/useStataUSDC/useStataUSDC.ts
> +export function useStataUSDC(customNetwork?: Network) {
we have `useStaticAaveUSDC` in code, use that instead

2024-10-10 08:34 UTC, noisekit commented on liquidity/lib/useStataUSDCRate/useStataUSDCRate.ts
> +export function useStataUSDCRate(customNetwork?: Network) {
we have `useStaticAaveUSDCRate` in code, use that instead

2024-10-11 11:49 UTC, noisekit commented on liquidity/ui/src/components/Manage/CollateralStats.tsx
> +                    return `${currency(new Wei(val, 27).div(stataUSDCRate || ONEWEI))} stataUSDC`;
```suggestion
                    return `${currency(new Wei(val, 27).div(stataUSDCRate || ONEWEI))} Static aUSDC`;
```

2024-10-11 11:50 UTC, noisekit approved these changes

2024-10-16 12:09 UTC, noisekit commented on liquidity/ui/src/components/Pools/PoolCards/PoolRow.tsx
> +              {isBase && collateralType.symbol === 'stataUSDC' && stataUSDC
reminder that symbol on Base Mainnet is `stataBasUSDC` 


https://github.com/Synthetixio/v3-contracts/blob/master/8453-andromeda/collateralTokens.json#L34-L49


and `stataUSDC` on Base Sepolia

https://github.com/Synthetixio/v3-contracts/blob/master/84532-andromeda/collateralTokens.json#L34-L49

2024-11-19 03:58 UTC, noisekit commented
all e2e tests pass when run locally

2024-11-19 03:58 UTC, merged